print 'Current Commands Are:'
print '!online                          | Use this to test if the bot is online'
print '#<text here>                 | Chat to the AI about stuff'
print '!dox <username/email> | Attempts to dox the specified username/email'
print '!whois <site/ip>            | Replies back with whois data of site/ip'
print '!quote                          | Replies back with a random sometimes wise quote'
print '!resolve <username>    | Skype Resolve, resolve usernames for you'